INSERT INTO artistes (nom_artiste, biographie) VALUES
('Alice Wonderland', 'Alice Wonderland est une chanteuse pop reconnue pour ses mélodies envoûtantes et ses paroles introspectives.'),
('Bob Steel', 'Bob Steel est un musicien de rock légendaire avec un style unique qui combine énergie brute et virtuosité.'),
('Charlie Velvet', 'Charlie Velvet est une artiste indie qui mélange folk et électro, créant des sons doux et mélodieux.'),
('Diana Storm', 'Diana Storm est une auteure-compositrice-interprète de musique R&B, connue pour sa voix puissante et ses ballades émotionnelles.'),
('Elvis Fuego', 'Un iconique chanteur de rock latino, Elvis Fuego fusionne les rythmes traditionnels avec des influences modernes.'),
('Freddie Moon', 'Freddie Moon est un chanteur pop britannique, célèbre pour ses tubes dansants et ses paroles optimistes.'),
('Grace Phoenix', 'Grace Phoenix est une artiste alternative avec des chansons abordant des thèmes de liberté et d\'espoir.'),
('Hugo Blitz', 'Hugo Blitz, le maître du métal symphonique, fait résonner ses compositions grandioses à travers le monde.'),
('Isla Blue', 'Isla Blue est une chanteuse folk-acoustique, dont les chansons sont empreintes de poésie et de douceur.'),
('Jack Rockwell', 'Jack Rockwell est un artiste rock passionné, connu pour ses performances explosives et ses riffs puissants.'),
('Kara Swift', 'Kara Swift est une star du pop-country, avec des mélodies accrocheuses et une voix unique.'),
('Luca Dark', 'Luca Dark est un DJ et producteur de musique électronique, créant des beats hypnotiques et des mixes énergétiques.'),
('Maya Sun', 'Maya Sun est une compositrice de musique ambient, créant des paysages sonores apaisants et mystiques.'),
('Nathan Cross', 'Nathan Cross est un chanteur de jazz et blues, célèbre pour sa voix rauque et sa capacité à improviser.'),
('Olivia Rain', 'Olivia Rain est une chanteuse soul avec une voix envoûtante et des ballades qui touchent le cœur.'),
('Pablo Rojas', 'Pablo Rojas est un guitariste et chanteur de flamenco, fusionnant le traditionnel avec des influences modernes.'),
('Quinn Rivers', 'Quinn Rivers est une artiste électronique alternative, explorant des sonorités expérimentales et des textures sonores uniques.'),
('Rita Blaze', 'Rita Blaze est une chanteuse pop-punk avec des paroles percutantes et une énergie débordante sur scène.'),
('Steve Hawk', 'Steve Hawk est un chanteur et compositeur de musique acoustique, connu pour ses chansons mélancoliques et ses concerts intimes.'),
('Tara Snow', 'Tara Snow est une auteure-compositrice de musique folk, créant des hymnes mélodiques sur l\'amour et la nature.');
